

variables:
  Solution: UOKO.SSO.sln
before_script:
  - 'echo off'
stages:
  - nugetrestore
  - build
nugetrestore:
  stage: nugetrestore
  script:
     - 'cd .nuget'
     - 'echo restoring..'
     - 'nuget restore "../%Solution%"'
     - 'cd ..'
     - 'echo restored'
  only:
    - master
  tags:
    - zhipingrunner

build:
  stage: build
  script:
     - 'echo building..'
     - '"%SystemRoot%\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe" "%Solution%" /t:Build /property:Configuration=Debug /p:VisualStudioVersion=12.0'
  only:
    - master
  tags:
    - zhipingrunner

